package models

// AccPayable representa un registro de cuenta por pagar.
type AccPayable struct {
	CodSucu    *string  `json:"codsucu"`
	CodProv    *string  `json:"codprov"`
	NroRegi    *int     `json:"nroregi"`
	FechaI     *string  `json:"fechai"`
	FechaE     *string  `json:"fechae"`
	FechaT     *string  `json:"fechat"`
	FechaR     *string  `json:"fechar"`
	FechaV     *string  `json:"fechav"`
	CodEsta    *string  `json:"codesta"`
	CodUsua    *string  `json:"codusua"`
	CodOper    *string  `json:"codoper"`
	NumeroD    *string  `json:"numerod"`
	NumeroN    *string  `json:"numeron"`
	NroCtrol   *string  `json:"nroctrol"`
	FromTran   *int     `json:"fromtran"`
	TipoCxP    *string  `json:"tipocxp"`
	TipoSus    *int     `json:"tiposus"`
	TipoTraE   *int     `json:"tipotrae"`
	NroEstable *string  `json:"nroestable"`
	PtoEmision *string  `json:"ptoemision"`
	AutSRI     *string  `json:"autsri"`
	CodTarj    *string  `json:"codtarj"`
	Moneda     *string  `json:"moneda"`
	Factor     *float64 `json:"factor"`
	MontoMex   *float64 `json:"montomex"`
	SaldoMex   *float64 `json:"saldomex"`
	Document   *string  `json:"document"`
	Notas1     *string  `json:"notas1"`
	Notas2     *string  `json:"notas2"`
	Notas3     *string  `json:"notas3"`
	Notas4     *string  `json:"notas4"`
	Notas5     *string  `json:"notas5"`
	Notas6     *string  `json:"notas6"`
	Notas7     *string  `json:"notas7"`
	Notas8     *string  `json:"notas8"`
	Notas9     *string  `json:"notas9"`
	Notas10    *string  `json:"notas10"`
	Monto      *float64 `json:"monto"`
	Debitos    *float64 `json:"debitos"`
	Creditos   *float64 `json:"creditos"`
	MontoNeto  *float64 `json:"montoneto"`
	MtoTax     *float64 `json:"mtotax"`
	RetenIVA   *float64 `json:"reteniva"`
	Saldo      *float64 `json:"saldo"`
	SaldoOrg   *float64 `json:"saldoorg"`
	SaldoAct   *float64 `json:"saldoact"`
	EsLibroI   *float64 `json:"eslibroi"`
	BaseImpo   *float64 `json:"baseimpo"`
	TExento    *float64 `json:"texento"`
	CancelI    *float64 `json:"canceli"`
	CancelA    *float64 `json:"cancela"`
	CancelE    *float64 `json:"cancele"`
	CancelC    *float64 `json:"cancelc"`
	CancelT    *float64 `json:"cancelt"`
	CancelG    *float64 `json:"cancelg"`
	CancelD    *float64 `json:"canceld"`
	EsUnPago   *int     `json:"esunpago"`
	EsReten    *int     `json:"esreten"`
	DetalChq   *string  `json:"detalchq"`
	AfectaCom  *int     `json:"afectacom"`
	Descrip    *string  `json:"descrip"`
	ID3        *string  `json:"id3"`
	NroOPago   *string  `json:"nroopago"`
	NroUnico   *int     `json:"nrounico"`
	ID         *int     `json:"id"`
}
