package models

// AccReceivable representa un registro de cuenta por cobrar.
type AccReceivable struct {
	CodSucu    *string  `json:"codsucu"`
	CodClie    *string  `json:"codclie"`
	NroTurno   *int     `json:"nroturno"`
	NroRegi    *int     `json:"nroregi"`
	FechaI     *string  `json:"fechai"`
	FechaE     *string  `json:"fechae"`
	FechaV     *string  `json:"fechav"`
	FechaT     *string  `json:"fechat"`
	FechaR     *string  `json:"fechar"`
	CodEsta    *string  `json:"codesta"`
	CodUsua    *string  `json:"codusua"`
	CodOper    *string  `json:"codoper"`
	CodVend    *string  `json:"codvend"`
	CodTarj    *string  `json:"codtarj"`
	NumeroD    *string  `json:"numerod"`
	NumeroF    *string  `json:"numerof"`
	NumeroP    *string  `json:"numerop"`
	NumeroT    *string  `json:"numerot"`
	NumeroN    *string  `json:"numeron"`
	NroCtrol   *string  `json:"nroctrol"`
	FromTran   *int     `json:"fromtran"`
	TipoCxC    *string  `json:"tipocxc"`
	TipoTraE   *int     `json:"tipotrae"`
	AutSRI     *string  `json:"autsri"`
	NroEstable *string  `json:"nroestable"`
	PtoEmision *string  `json:"ptoemision"`
	Moneda     *string  `json:"moneda"`
	Factor     *float64 `json:"factor"`
	MontoMex   *float64 `json:"montomex"`
	SaldoMex   *float64 `json:"saldomex"`
	Document   *string  `json:"document"`
	Notas1     *string  `json:"notas1"`
	Notas2     *string  `json:"notas2"`
	Notas3     *string  `json:"notas3"`
	Notas4     *string  `json:"notas4"`
	Notas5     *string  `json:"notas5"`
	Notas6     *string  `json:"notas6"`
	Notas7     *string  `json:"notas7"`
	Notas8     *string  `json:"notas8"`
	Notas9     *string  `json:"notas9"`
	Notas10    *string  `json:"notas10"`
	Monto      *float64 `json:"monto"`
	Debitos    *float64 `json:"debitos"`
	Creditos   *float64 `json:"creditos"`
	MontoNeto  *float64 `json:"montoneto"`
	MtoTax     *float64 `json:"mtotax"`
	RetenIVA   *float64 `json:"reteniva"`
	OrgTax     *float64 `json:"orgtax"`
	Saldo      *float64 `json:"saldo"`
	SaldoOrg   *float64 `json:"saldoorg"`
	SaldoAct   *float64 `json:"saldoact"`
	EsLibroI   *int     `json:"eslibroi"`
	BaseImpo   *float64 `json:"baseimpo"`
	TExento    *float64 `json:"texento"`
	CancelI    *float64 `json:"canceli"`
	CancelA    *float64 `json:"cancela"`
	CancelE    *float64 `json:"cancele"`
	CancelC    *float64 `json:"cancelc"`
	CancelT    *float64 `json:"cancelt"`
	CancelG    *float64 `json:"cancelg"`
	CancelP    *float64 `json:"cancelp"`
	CancelD    *float64 `json:"canceld"`
	Comision   *float64 `json:"comision"`
	DetalChq   *string  `json:"detalchq"`
	EsUnPago   *int     `json:"esunpago"`
	AfectaVta  *int     `json:"afectavta"`
	AfectaComi *int     `json:"afectacomi"`
	EsChqDev   *int     `json:"eschqdev"`
	EsReten    *int     `json:"esreten"`
	UltIntMora *string  `json:"ultintmora"`
	PrxVisita  *string  `json:"prxvisita"`
	TipoReg    *int     `json:"tiporeg"`
	NroUnico   *int     `json:"nrounico"`
	ID         *int     `json:"id"`
}
