package models

// CompanySettings representa la configuración de la empresa desde una API.
type CompanySettings struct {
	ID               int      `json:"id"`
	CodSucu          string   `json:"codsucu"`
	Descrip          string   `json:"descrip"`
	Direc1           string   `json:"direc1"`
	Direc2           string   `json:"direc2"`
	Email            *string  `json:"email"`
	Telef            string   `json:"telef"`
	RIF              string   `json:"rif"`
	NroSerial        string   `json:"nroserial"`
	KeySerial        string   `json:"keyserial"`
	FechaUV          *string  `json:"fechauv"`
	ZipCode          *string  `json:"zipcode"`
	Municipio        int      `json:"municipio"`
	Ciudad           int      `json:"ciudad"`
	Estado           int      `json:"estado"`
	Pais             int      `json:"pais"`
	SPais            string   `json:"spais"`
	SEstado          string   `json:"sestado"`
	SCiudad          string   `json:"sciudad"`
	SMunicipio       string   `json:"smunicipio"`
	CodTaxS          string   `json:"codtaxs"`
	CostoMes         int      `json:"costomes"`
	CorrelPrd        int      `json:"correlprd"`
	IDAppNot         int      `json:"idappnot"`
	IDVersion        int      `json:"idversion"`
	IDVerXtra        int      `json:"idverxtra"`
	MesCurso         string   `json:"mescurso"`
	Factor           float64  `json:"factor"`
	FactorM          float64  `json:"factorm"`
	UsaFactorM       int      `json:"usafactorm"`
	FechaUP          string   `json:"fechaup"`
	MesTran          int      `json:"mestran"`
	MesOC            int      `json:"mesoc"`
	MesPrf           int      `json:"mesprf"`
	MesesPtos        int      `json:"mesesptos"`
	ValorPtos        float64  `json:"valorptos"`
	ValorPtosV       float64  `json:"valorptosv"`
	FechaUC          string   `json:"fechauc"`
	MtoExtraG        int      `json:"mtoextrag"`
	ImpFleteV        int      `json:"impfletev"`
	ImpFleteC        int      `json:"impfletec"`
	RetenIVA         float64  `json:"reteniva"`
	AutoReten        float64  `json:"autoreten"`
	PorcReten        float64  `json:"porctreten"`
	PedirNCtrl       int      `json:"pedirnctrl"`
	Redond           int      `json:"redond"`
	RedTotal         int      `json:"redtotal"`
	ObliOper         int      `json:"oblioper"`
	PaswLim          int      `json:"paswlim"`
	Settings         *string  `json:"settings"`
	MontoMin         int      `json:"montomin"`
	SimbFac          string   `json:"simbfac"`
	EsMoneda         int      `json:"esmoneda"`
	CorrelUnc        int      `json:"correlunc"`
	FillCorrel       int      `json:"fillcorrel"`
	Imagen           *string  `json:"imagen"`
	TipoFac          int      `json:"tipofac"`
	TipoDef          int      `json:"tipodef"`
	NroEstable       *string  `json:"nroestable"`
	RUCUser          *string  `json:"rucuser"`
	RUCPwd           *string  `json:"rucpwd"`
	SerieFacE        string   `json:"serieface"`
	CorrelEstaC      int      `json:"correlestac"`
	ImpuestoD        float64  `json:"impuestod"`
	IMailHost        string   `json:"imailhost"`
	IMailPort        int      `json:"imailport"`
	IMailUser        string   `json:"imailuser"`
	IMailPwd         string   `json:"imailpwd"`
	IMailSender      string   `json:"imailsender"`
	IMailSSL         int      `json:"imailssl"`
	TokenEmpresa     string   `json:"tokenempresa"`
	TokenSecuencial  string   `json:"tokensecuencial"`
	FacWSRVURL       string   `json:"facwsrvurl"`
	TipoPrv          int      `json:"tipoprv"`
	TipoAtr          int      `json:"tipoatr"`
	CodTaxD1         *string  `json:"codtaxd1"`
	CodTaxD2         *string  `json:"codtaxd2"`
	MtoTaxD1         float64  `json:"mtotaxd1"`
	MtoTaxD2         float64  `json:"mtotaxd2"`
	DctoAplica       int      `json:"dctoaplica"`
	ImpT             int      `json:"impt"`
	PrecioI          float64  `json:"precioi"`
	CreatedAt        string   `json:"createdat"`
	UpdatedAt        *string  `json:"updatedat"`
}