package models

// InventoryItem representa un ítem en una operación de inventario.
type InventoryItem struct {
	CodSucu    string   `json:"codsucu"`
	TipoOpi    string   `json:"tipoopi"`
	NumeroD    string   `json:"numerod"`
	NroLinea   int      `json:"nrolinea"`
	NroLineaC  int      `json:"nrolineac"`
	CodItem    string   `json:"coditem"`
	CodUbic    string   `json:"codubic"`
	CodUbic2   *string  `json:"codubic2"`
	Descrip1   string   `json:"descrip1"`
	Descrip2   *string  `json:"descrip2"`
	Descrip3   *string  `json:"descrip3"`
	Descrip4   *string  `json:"descrip4"`
	Descrip5   *string  `json:"descrip5"`
	Descrip6   *string  `json:"descrip6"`
	Descrip7   *string  `json:"descrip7"`
	Descrip8   *string  `json:"descrip8"`
	Descrip9   *string  `json:"descrip9"`
	Descrip10  *string  `json:"descrip10"`
	Refere     *string  `json:"refere"`
	Signo      int      `json:"signo"`
	Tara       int      `json:"tara"`
	Factor     float64  `json:"factor"`
	CantidadD  float64  `json:"cantidadd"`
	CantidadT  float64  `json:"cantidadt"`
	Cantidad   float64  `json:"cantidad"`
	CantidadO  float64  `json:"cantidado"`
	ExistantU  float64  `json:"existantu"`
	Existant   float64  `json:"existant"`
	ExistantU2 float64  `json:"existantu2"`
	Existant2  float64  `json:"existant2"`
	CantidadC  float64  `json:"cantidadc"`
	CantidadU  float64  `json:"cantidadu"`
	CantidadA  float64  `json:"cantidada"`
	CantidadUA float64  `json:"cantidadua"`
	Costo      float64  `json:"costo"`
	Descto     float64  `json:"descto"`
	CodMeca    *string  `json:"codmeca"`
	TotalItem  float64  `json:"totalitem"`
	NroUnicol  float64  `json:"nrounicol"`
	NroLote    *string  `json:"nrolote"`
	Precio     float64  `json:"precio"`
	PrecioU    float64  `json:"preciou"`
	FechaE     string   `json:"fechae"`
	FechaL     string   `json:"fechal"`
	FechaV     *string  `json:"fechav"`
	EsServ     int      `json:"esserv"`
	EsUnid     int      `json:"esunid"`
	EsFreeP    int      `json:"esfreep"`
	EsPesa     int      `json:"espesa"`
	EsExento   int      `json:"esexento"`
	UsaServ    int      `json:"usaserv"`
	DesLote    int      `json:"deslote"`
	DesSeri    int      `json:"desseri"`
	ID         int      `json:"id"`
}