package models

// Invoice representa una factura de venta.
type Invoice struct {
	CodSucu     *string  `json:"codsucu"`
	TipoFac     *string  `json:"tipofac"`
	NumeroD     *string  `json:"numerod"`
	NroTurno    *int     `json:"nroturno"`
	NroCtrol    *string  `json:"nroctrol"`
	FromTran    *int     `json:"fromtran"`
	EstadoFE    *int     `json:"estadofe"`
	CodEsta     *string  `json:"codesta"`
	CodUsua     *string  `json:"codusua"`
	CodTran     *string  `json:"codtran"`
	CodTarj     *string  `json:"codtarj"`
	EsCorrel    *int     `json:"escorrel"`
	CodConv     *string  `json:"codconv"`
	Signo       *int     `json:"signo"`
	FechaT      *string  `json:"fechat"`
	TipoDev     *int     `json:"tipodev"`
	OTipo       *string  `json:"otipo"`
	ONumero     *string  `json:"onumero"`
	NumeroC     *string  `json:"numeroc"`
	NumeroT     *string  `json:"numerot"`
	NumeroR     *string  `json:"numeror"`
	TipoTraE    *int     `json:"tipotrae"`
	AutSRI      *string  `json:"autsri"`
	NroEstable  *string  `json:"nroestable"`
	PtoEmision  *string  `json:"ptoemision"`
	NumeroU     *string  `json:"numerou"`
	NumeroF     *string  `json:"numerof"`
	NumeroNCF   *string  `json:"numeroncf"`
	NumeroP     *string  `json:"numerop"`
	NumeroE     *string  `json:"numeroe"`
	NumeroZ     *string  `json:"numeroz"`
	Moneda      *string  `json:"moneda"`
	Factor      *float64 `json:"factor"`
	MontoMex    *float64 `json:"montomex"`
	CodClie     *string  `json:"codclie"`
	CodVend     *string  `json:"codvend"`
	CodUbic     *string  `json:"codubic"`
	Descrip     *string  `json:"descrip"`
	Direc1      *string  `json:"direc1"`
	Direc2      *string  `json:"direc2"`
	Direc3      *string  `json:"direc3"`
	ZipCode     *string  `json:"zipcode"`
	Telef       *string  `json:"telef"`
	ID3         *string  `json:"id3"`
	Monto       *float64 `json:"monto"`
	MtoTax      *float64 `json:"mtotax"`
	Fletes      *float64 `json:"fletes"`
	TGravable   *float64 `json:"tgravable"`
	TGravable0  *float64 `json:"tgravable0"`
	TExento     *float64 `json:"texento"`
	CostoPrd    *float64 `json:"costoprd"`
	CostoSrv    *float64 `json:"costosrv"`
	DesctoP     *float64 `json:"desctop"`
	RetenIVA    *float64 `json:"reteniva"`
	FechaR      *string  `json:"fechar"`
	FechaI      *string  `json:"fechai"`
	FechaE      *string  `json:"fechae"`
	FechaV      *string  `json:"fechav"`
	MtoTotal    *float64 `json:"mtototal"`
	Contado     *float64 `json:"contado"`
	Credito     *float64 `json:"credito"`
	CancelI     *float64 `json:"canceli"`
	CancelA     *float64 `json:"cancela"`
	CancelE     *float64 `json:"cancele"`
	CancelC     *float64 `json:"cancelc"`
	CancelT     *float64 `json:"cancelt"`
	CancelG     *float64 `json:"cancelg"`
	CancelP     *float64 `json:"cancelp"`
	Cambio      *float64 `json:"cambio"`
	MtoExtra    *float64 `json:"mtoextra"`
	ValorPtos   *float64 `json:"valorptos"`
	Descto1     *float64 `json:"descto1"`
	PctAnual    *float64 `json:"pctanual"`
	MtoInt1     *float64 `json:"mtoint1"`
	Descto2     *float64 `json:"descto2"`
	PctManejo   *float64 `json:"pctmanejo"`
	MtoInt2     *float64 `json:"mtoint2"`
	SaldoAct    *float64 `json:"saldoact"`
	MtoPagos    *float64 `json:"mtopagos"`
	MtoNCredito *float64 `json:"mtoncredito"`
	MtoNDebito  *float64 `json:"mtondebito"`
	MtoFinanc   *float64 `json:"mtofinanc"`
	DetalChq    *string  `json:"detalchq"`
	TotalPrd    *float64 `json:"totalprd"`
	TotalSrv    *float64 `json:"totalsrv"`
	OrdenC      *string  `json:"ordenc"`
	CodOper     *string  `json:"codoper"`
	NGiros      *int     `json:"ngiros"`
	NMeses      *int     `json:"nmeses"`
	MtoComiVta  *float64 `json:"mtocomivta"`
	MtoComiCob  *float64 `json:"mtocomicob"`
	MtoComiVtaD *float64 `json:"mtocomivtad"`
	MtoComiCobD *float64 `json:"mtocomicobd"`
	ImpuestoD   *float64 `json:"impuestod"`
	CancelTips  *float64 `json:"canceltips"`
	NroUnicol   *int     `json:"nrounicol"`
	CodAlte     *string  `json:"codalte"`
	Parcial     *int     `json:"parcial"`
	Notas1      *string  `json:"notas1"`
	Notas2      *string  `json:"notas2"`
	Notas3      *string  `json:"notas3"`
	Notas4      *string  `json:"notas4"`
	Notas5      *string  `json:"notas5"`
	Notas6      *string  `json:"notas6"`
	Notas7      *string  `json:"notas7"`
	Notas8      *string  `json:"notas8"`
	Notas9      *string  `json:"notas9"`
	Notas10     *string  `json:"notas10"`
	NroUnico    *int     `json:"nrounico"`
	ID          *int     `json:"id"`
}
