package models

// InvoiceItem representa los datos de un ítem en una factura.
type InvoiceItem struct {
	CodSucu    *string  `json:"codsucu"`
	TipoFac    *string  `json:"tipofac"`
	NumeroD    *string  `json:"numerod"`
	OTipo      *string  `json:"otipo"`
	ONumero    *string  `json:"onumero"`
	ONroLinea  *int     `json:"onrolinea"`
	ONroLineaC *int     `json:"onrolineac"`
	NumeroE    *string  `json:"numeroe"`
	NroLinea   *int     `json:"nrolinea"`
	NroLineaC  *int     `json:"nrolineac"`
	CodItem    *string  `json:"coditem"`
	CodUbic    *string  `json:"codubic"`
	CodUsua    *string  `json:"codusua"`
	CodAuth    *string  `json:"codauth"`
	CodMeca    *string  `json:"codmeca"`
	CodVend    *string  `json:"codvend"`
	Descrip1   *string  `json:"descrip1"`
	Descrip2   *string  `json:"descrip2"`
	Descrip3   *string  `json:"descrip3"`
	Descrip4   *string  `json:"descrip4"`
	Descrip5   *string  `json:"descrip5"`
	Descrip6   *string  `json:"descrip6"`
	Descrip7   *string  `json:"descrip7"`
	Descrip8   *string  `json:"descrip8"`
	Descrip9   *string  `json:"descrip9"`
	Descrip10  *string  `json:"descrip10"`
	Refere     *string  `json:"refere"`
	Signo      *int     `json:"signo"`
	CantMayor  *float64 `json:"cantmayor"`
	Cantidad   *float64 `json:"cantidad"`
	CantidadD  *float64 `json:"cantidadd"`
	CantidadT  *float64 `json:"cantidadt"`
	CantidadO  *float64 `json:"cantidado"`
	CantidadA  *float64 `json:"cantidada"`
	CantidadU  *float64 `json:"cantidadu"`
	CantidadUA *float64 `json:"cantidadua"`
	ExistantU  *float64 `json:"existantu"`
	Existant   *float64 `json:"existant"`
	Tara       *int     `json:"tara"`
	Factor     *float64 `json:"factor"`
	TotalItem  *float64 `json:"totalitem"`
	Costo      *float64 `json:"costo"`
	TipoPVP    *int     `json:"tipopvp"`
	Precio     *float64 `json:"precio"`
	PrecioI    *float64 `json:"precioi"`
	MtoTax     *float64 `json:"mtotax"`
	MtoTaxO    *float64 `json:"mtotaxo"`
	PriceO     *float64 `json:"priceo"`
	Descto     *float64 `json:"descto"`
	NroUnicol  *float64 `json:"nrounicol"`
	NroLote    *string  `json:"nrolote"`
	FechaE     *string  `json:"fechae"`
	FechaL     *string  `json:"fechal"`
	FechaV     *string  `json:"fechav"`
	EsServ     *int     `json:"esserv"`
	EsUnid     *int     `json:"esunid"`
	EsFreeP    *int     `json:"esfreep"`
	EsPesa     *int     `json:"espesa"`
	EsExento   *int     `json:"esexento"`
	UsaServ    *int     `json:"usaserv"`
	DesLote    *int     `json:"deslote"`
	DesSeri    *int     `json:"desseri"`
	DesComp    *int     `json:"descomp"`
	TipoData   *int     `json:"tipodata"`
	ID         *int     `json:"id"`
}
