package models

// Product representa los datos de un producto de una API.
type Product struct {
	ID        *int     `json:"id"`
	CodProd   *string  `json:"codprod"`
	Descrip   *string  `json:"descrip"`
	CodInst   *int     `json:"codinst"`
	Activo    *int     `json:"activo"`
	Descrip2  *string  `json:"descrip2"`
	Descrip3  *string  `json:"descrip3"`
	Refere    *string  `json:"refere"`
	Marca     *string  `json:"marca"`
	Unidad    *string  `json:"unidad"`
	UndEmpaq  *string  `json:"undempaq"`
	CantEmpaq *int     `json:"cantempaq"`
	Precio1   *float64 `json:"precio1"`
	PrecioI1  *float64 `json:"precioi1"`
	PrecioIU1 *float64 `json:"precioiu1"`
	Precio2   *float64 `json:"precio2"`
	PrecioU2  *float64 `json:"preciou2"`
	PrecioI2  *float64 `json:"precioi2"`
	PrecioIU2 *float64 `json:"precioiu2"`
	Precio3   *float64 `json:"precio3"`
	PrecioU3  *float64 `json:"preciou3"`
	PrecioI3  *float64 `json:"precioi3"`
	PrecioIU3 *float64 `json:"precioiu3"`
	PrecioU   *float64 `json:"preciou"`
	CostAct   *float64 `json:"costact"`
	CostPro   *float64 `json:"costpro"`
	CostAnt   *float64 `json:"costant"`
	Existen   *float64 `json:"existen"`
	ExUnidad  *int     `json:"exunidad"`
	Compro    *int     `json:"compro"`
	Pedido    *int     `json:"pedido"`
	Minimo    *int     `json:"minimo"`
	Maximo    *int     `json:"maximo"`
	Tara      *int     `json:"tara"`
	Factor    *float64 `json:"factor"`
	DesComp   *int     `json:"descomp"`
	DesComi   *int     `json:"descomi"`
	DesSeri   *int     `json:"desseri"`
	EsReten   *int     `json:"esreten"`
	DesLote   *int     `json:"deslote"`
	DesVence  *int     `json:"desvence"`
	EsImport  *int     `json:"esimport"`
	EsExento  *int     `json:"esexento"`
	EsEnSer   *int     `json:"esenser"`
	EsOferta  *int     `json:"esoferta"`
	EsPesa    *int     `json:"espesa"`
	EsEmpaque *int     `json:"esempaque"`
	ExDecimal *int     `json:"exdecimal"`
	DiasEntr  *int     `json:"diasentr"`
	FechaUV   *string  `json:"fechauv"`
	FechaUC   *string  `json:"fechauc"`
	DiasTole  *int     `json:"diastole"`
	Peso      *int     `json:"peso"`
	Volumen   *int     `json:"volumen"`
	UndVol    *string  `json:"undvol"`
	PriceEx   *int     `json:"priceex"`
	CreatedAt *string  `json:"createdat"`
	UpdatedAt *string  `json:"updatedat"`
}
