package models

// Purchase representa una factura de compra.
type Purchase struct {
	CodSucu     *string  `json:"codsucu"`
	TipoCom     *string  `json:"tipocom"`
	NumeroD     *string  `json:"numerod"`
	CodProv     *string  `json:"codprov"`
	FromTran    *int     `json:"fromtran"`
	NroCtrol    *string  `json:"nroctrol"`
	CodEsta     *string  `json:"codesta"`
	CodUsua     *string  `json:"codusua"`
	Signo       *int     `json:"signo"`
	FechaT      *string  `json:"fechat"`
	OTipo       *string  `json:"otipo"`
	ONumero     *string  `json:"onumero"`
	NumeroP     *string  `json:"numerop"`
	NumeroE     *string  `json:"numeroe"`
	NumeroC     *string  `json:"numeroc"`
	NumeroN     *string  `json:"numeron"`
	NumeroR     *string  `json:"numeror"`
	TipoSus     *int     `json:"tiposus"`
	TipoTraE    *int     `json:"tipotrae"`
	NroEstable  *string  `json:"nroestable"`
	PtoEmision  *string  `json:"ptoemision"`
	AutSRI      *string  `json:"autsri"`
	FechaP      *string  `json:"fechap"`
	CodTarj     *string  `json:"codtarj"`
	Moneda      *string  `json:"moneda"`
	Factor      *float64 `json:"factor"`
	MontoMex    *float64 `json:"montomex"`
	CodUbic     *string  `json:"codubic"`
	Descrip     *string  `json:"descrip"`
	Direc1      *string  `json:"direc1"`
	Direc2      *string  `json:"direc2"`
	ZipCode     *string  `json:"zipcode"`
	Telef       *string  `json:"telef"`
	ID3         *string  `json:"id3"`
	Monto       *float64 `json:"monto"`
	OtrosC      *float64 `json:"otrosc"`
	MtoTax      *float64 `json:"mtotax"`
	Fletes      *float64 `json:"fletes"`
	TGravable   *float64 `json:"tgravable"`
	TGravable0  *float64 `json:"tgravable0"`
	TExento     *float64 `json:"texento"`
	DesctoP     *float64 `json:"desctop"`
	RetenIVA    *float64 `json:"reteniva"`
	FechaI      *string  `json:"fechai"`
	FechaR      *string  `json:"fechar"`
	FechaE      *string  `json:"fechae"`
	FechaV      *string  `json:"fechav"`
	CancelI     *float64 `json:"canceli"`
	CancelE     *float64 `json:"cancele"`
	CancelT     *float64 `json:"cancelt"`
	CancelC     *float64 `json:"cancelc"`
	CancelA     *float64 `json:"cancela"`
	CancelG     *float64 `json:"cancelg"`
	MtoTotal    *float64 `json:"mtototal"`
	Contado     *float64 `json:"contado"`
	Credito     *float64 `json:"credito"`
	SaldoAct    *float64 `json:"saldoact"`
	MtoPagos    *float64 `json:"mtopagos"`
	MtoNCredito *float64 `json:"mtoncredito"`
	MtoNDebito  *float64 `json:"mtondebito"`
	Descto1     *float64 `json:"descto1"`
	MtoInt1     *float64 `json:"mtoint1"`
	Descto2     *float64 `json:"descto2"`
	MtoInt2     *float64 `json:"mtoint2"`
	MtoFinanc   *float64 `json:"mtofinanc"`
	DetalChq    *string  `json:"detalchq"`
	TotalPrd    *float64 `json:"totalprd"`
	TotalSrv    *float64 `json:"totalsrv"`
	OrdenC      *string  `json:"ordenc"`
	CodOper     *string  `json:"codoper"`
	NGiros      *int     `json:"ngiros"`
	NMeses      *int     `json:"nmeses"`
	Notas1      *string  `json:"notas1"`
	Notas2      *string  `json:"notas2"`
	Notas3      *string  `json:"notas3"`
	Notas4      *string  `json:"notas4"`
	Notas5      *string  `json:"notas5"`
	Notas6      *string  `json:"notas6"`
	Notas7      *string  `json:"notas7"`
	Notas8      *string  `json:"notas8"`
	Notas9      *string  `json:"notas9"`
	Notas10     *string  `json:"notas10"`
	NroUnico    *int     `json:"nrounico"`
	ID          *int     `json:"id"`
}
