package models

// PurchaseItem representa un ítem en una factura de compra.
type PurchaseItem struct {
	CodSucu     string   `json:"codsucu"`
	TipoCom     string   `json:"tipocom"`
	NumeroD     string   `json:"numerod"`
	CodProv     string   `json:"codprov"`
	OTipo       *string  `json:"otipo"`
	ONumero     *string  `json:"onumero"`
	NroLinea    *int     `json:"nrolinea"`
	NroLineaC   *int     `json:"nrolineac"`
	CodItem     *string  `json:"coditem"`
	CodUbic     *string  `json:"codubic"`
	Descrip1    *string  `json:"descrip1"`
	Descrip2    *string  `json:"descrip2"`
	Descrip3    *string  `json:"descrip3"`
	Descrip4    *string  `json:"descrip4"`
	Descrip5    *string  `json:"descrip5"`
	Descrip6    *string  `json:"descrip6"`
	Descrip7    *string  `json:"descrip7"`
	Descrip8    *string  `json:"descrip8"`
	Descrip9    *string  `json:"descrip9"`
	Descrip10   *string  `json:"descrip10"`
	Refere      *string  `json:"refere"`
	Signo       *int     `json:"signo"`
	Tara        *int     `json:"tara"`
	CantidadD   *float64 `json:"cantidadd"`
	Cantidad    *float64 `json:"cantidad"`
	CantidadO   *float64 `json:"cantidado"`
	CantidadT   *float64 `json:"cantidadt"`
	ExistantU   *float64 `json:"existantu"`
	Existant    *float64 `json:"existant"`
	Faltante    *float64 `json:"faltante"`
	CantidadU   *float64 `json:"cantidadu"`
	CantidadA   *float64 `json:"cantidada"`
	CantidadUA  *float64 `json:"cantidadua"`
	Costo       *float64 `json:"costo"`
	MtoTax      *float64 `json:"mtotax"`
	CostoOrg    *float64 `json:"costorg"`
	CostoI      *float64 `json:"costoi"`
	TotalItem   *float64 `json:"totalitem"`
	Precio1     *float64 `json:"precio1"`
	PrecioI1    *float64 `json:"precioi1"`
	PrecioIU1   *float64 `json:"precioiu1"`
	Precio2     *float64 `json:"precio2"`
	PrecioU2    *float64 `json:"preciou2"`
	PrecioI2    *float64 `json:"precioi2"`
	PrecioIU2   *float64 `json:"precioiu2"`
	Precio3     *float64 `json:"precio3"`
	PrecioU3    *float64 `json:"preciou3"`
	PrecioI3    *float64 `json:"precioi3"`
	PrecioIU3   *float64 `json:"precioiu3"`
	PrecioU     *float64 `json:"preciou"`
	Descto      *int     `json:"descto"`
	NroUnicol   *int     `json:"nrounicol"`
	NroLote     *string  `json:"nrolote"`
	FechaE      *string  `json:"fechae"`
	FechaL      *string  `json:"fechal"`
	FechaV      *string  `json:"fechav"`
	EsServ      *int     `json:"esserv"`
	EsUnid      *int     `json:"esunid"`
	EsFreeP     *int     `json:"esfreep"`
	EsPesa      *int     `json:"espesa"`
	EsExento    *int     `json:"esexento"`
	UsaServ     *int     `json:"usaserv"`
	DesLote     *int     `json:"deslote"`
	DesSeri     *int     `json:"desseri"`
	ID          *int     `json:"id"`
}